### ISSUE TITLE
Can't create folders with an empty rule added

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/files_accesscontrol#18]
I can't create folders via web:
```
Exception: {"Message":"HTTP\/1.1 403 Access denied","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden","Code":0,"Trace":"#0 \/media\/psf\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1150): OCA\\DAV\\Connector\\Sabre\\Directory->createDirectory('asdfafsdfadsf')\n#1 \/media\/psf\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('asdfafsdfadsf', Object(Sabre\\DAV\\MkCol))\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/media\/psf\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/media\/psf\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#5 \/media\/psf\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/media\/psf\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#7 \/media\/psf\/nextcloud\/remote.php(165): require_once('\/media\/psf\/next...')\n#8 {main}","File":"\/media\/psf\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":174,"User":"admin"}	
```
cc @nickvergessen

**Comment by nickvergessen** [comment]
Well empty rule-group means it always matches, therefor it's the expected behaviour?

But I will see if we can add a way to not allow empty rule-groups for access-control

**Comment by blizzz** [comment]
With an empty rule group also an exception is logged on files:

```
{"reqId":"gRZnolOEShTqL5B79PpR","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\Files\ForbiddenException\",\"Message\":\"Access denied\",\"Code\":0,\"Trace\":\"
#0 /srv/http/nextcloud/master/apps/files_accesscontrol/lib/StorageWrapper.php(47): OCA\FilesAccessControl\Operation->checkFileAccess(Object(OCA\FilesAccessControl\StorageWrapper), 'thumbnails/6/32...')\
#1 /srv/http/nextcloud/master/apps/files_accesscontrol/lib/StorageWrapper.php(291): OCA\FilesAccessControl\StorageWrapper->checkFileAccess('thumbnails/6/32...')\
#2 /srv/http/nextcloud/master/lib/private/Files/View.php(1118): OCA\FilesAccessControl\StorageWrapper->fopen('thumbnails/6/32...', 'r')\
#3 /srv/http/nextcloud/master/lib/private/Files/View.php(963): OC\Files\View->basicOperation('fopen', '/thumbnails/6/3...', Array, 'r')\
#4 /srv/http/nextcloud/master/lib/private/Preview.php(821): OC\Files\View->fopen('thumbnails/6/32...', 'r')\
#5 /srv/http/nextcloud/master/lib/private/Preview.php(773): OC\Preview->getCachedPreview(6, 'thumbnails/6/32...')\
#6 /srv/http/nextcloud/master/lib/private/Preview.php(802): OC\Preview->getPreview()\
#7 /srv/http/nextcloud/master/core/ajax/preview.php(64): OC\Preview->showPreview()\
#8 /srv/http/nextcloud/master/lib/private/Route/Route.php(155) : runtime-created function(1): require_once('/srv/http/nextc...')\
#9 [internal function]: __lambda_func()\
#10 /srv/http/nextcloud/master/lib/private/Route/Router.php(298): call_user_func('\x00lambda_524', Array)\
#11 /srv/http/nextcloud/master/lib/base.php(969): OC\Route\Router->match('/core/preview.p...')\
#12 /srv/http/nextcloud/master/index.php(48): OC::handleRequest()\
#13 {main}\",\"File\":\"/srv/http/nextcloud/master/apps/files_accesscontrol/lib/Operation.php\",\"Line\":57}","level":3,"time":"2016-08-18T09:49:13+00:00","method":"GET","url":"/master/index.php/core/preview.png?file=%2Fwelcome.txt&c=16ecfbae913b255f2a07a20b3eac3d65&x=32&y=32&forceIcon=0","user":"yolo"}
```
