### ISSUE TITLE
file access control with file system tag or request URL doesn't work with shared files

### ISSUE THREAD

**Issue by fifh** [nextcloud/files_accesscontrol#83]
### Steps to reproduce
1. login as admin
2. create a folder "testfolder" with a sub-folder "test sub"
3. create a new file access control rule group : "Request URL" matches /.*\/testfolder.*/i
4. try to open the "testfolder" folder : you get a message "This operation is forbidden"
5. share the "testfolder" folder to another user (pbernard)
6. pbernard tries to open the "testfolder" folder

Same case with a file system tag : 

1. login as admin
2. create a folder "testfolder" and apply a restricted tag "confidential" to it
3. create a new file access control rule group : "File system tag" is tagged with "confidential (restricted)"
4. try to open the "testfolder" folder : you get a message "This operation is forbidden"
5. share the "testfolder" folder to another user (pbernard)
6. pbernard tries to open the "testfolder" folder

### Expected behaviour

I think pbernard should not be able to open the "testfolder" folder and should receive the same message "This operation is forbidden"

### Actual behaviour

pbernard can open the "testfolder" folder but he can't open the sub folder "test sub".
pbernard can edit document in the "testfolder" folder using Collabora Office.

### General server configuration

**Operating system:** Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.1.11 (apache2handler)

**Database:** mysql 5.5.56

**PHP version:** 7.1.11
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, smbclient, zip, Phar, libsmbclient, Zend OPcache

**LibreOffice Online version:** Collabora Online 2.1.5

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** regularly updated since ownCloud 8

**Where did you install Nextcloud from:** tar.gz from Nextcloud web site

**Are you using external storage, if yes which one:** 
    [0] => \OC\Files\Storage\Local
    [10] => \OCA\Files_External\Lib\Storage\SMB

**Windows server:** Windows server 2012 R2 (not used for this test)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
OpenLdap + Active Directory

**Signing status**
No errors have been found.

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - circles: 0.13.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_antivirus: 1.1.0
 - files_automatedtagging: 1.2.2
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.6
 - mood: 0.3.3
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - piwik: 0.3.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - richdocuments: 1.12.39
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.3
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
Disabled:
 - announcementcenter
 - dashboard
 - deck
 - encryption
 - groupfolders
 - ldapcontacts
 - ldaporg
 - news
 - spreed
 - user_external
 - user_saml
 - zimbradrive

```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "debug": true,
    "instanceid": "ocisk9esiwsh",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "test.arawa.fr",
        "vps213787.ovh.net"
    ],
    "datadirectory": "\/var\/www\/html\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/test.arawa.fr",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Paris",
    "loglevel": 0,
    "log_rotate_size": 10485760,
    "log_rotate_sizerotation": 10485760,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "session_keepalive": true,
    "installed": true,
    "appstore.experimental.enabled": true,
    "ldapIgnoreNamingRules": false,
    "theme": "",
    "maintenance": false,
    "activity_expire_days": 100,
    "trashbin_retention_obligation": "auto,20",
    "versions_retention_obligation": "auto,20",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "contact",
    "mail_domain": "hemmel.fr",
    "mail_smtpauth": 1,
    "mail_smtphost": "ssl0.ovh.net",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "",
    "ldapUserCleanupInterval": 5,
    "log_query": false,
    "mysql.utf8mb4": true,
    "enable_previews": true,
    "defaultapp": "activity,files"
}
```
</details>

<details>
        <summary>LDAP config s00</summary>

```
- hasMemberOfFilterSupport
- hasPagedResultSupport
- homeFolderNamingRule
- lastJpegPhotoLookup           : 0
- ldapAgentName                 : ***
- ldapAgentPassword             : ***
- ldapAttributesForGroupSearch
- ldapAttributesForUserSearch   : displayName;mail
- ldapBackupHost
- ldapBackupPort
- ldapBase                      : dc=arawa,dc=fr
- ldapBaseGroups                : dc=arawa,dc=fr
- ldapBaseUsers                 : dc=arawa,dc=fr
- ldapCacheTTL                  : 600
- ldapConfigurationActive       : 1
- ldapDefaultPPolicyDN
- ldapDynamicGroupMemberURL
- ldapEmailAttribute            : mail
- ldapExperiencedAdmin          : 0
- ldapExpertUUIDGroupAttr
- ldapExpertUUIDUserAttr
- ldapExpertUsernameAttr        : uid
- ldapGidNumber                 : gidNumber
- ldapGroupDisplayName          : cn
- ldapGroupFilter               : (&(|(objectclass=posixGroup)))
- ldapGroupFilterGroups
- ldapGroupFilterMode           : 0
- ldapGroupFilterObjectclass    : posixGroup
- ldapGroupMemberAssocAttr      : memberUid
- ldapHost                      : ***
- ldapIgnoreNamingRules
- ldapLoginFilter               : (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
- ldapLoginFilterAttributes
- ldapLoginFilterEmail          : 1
- ldapLoginFilterMode           : 0
- ldapLoginFilterUsername       : 1
- ldapNestedGroups              : 0
- ldapOverrideMainServer
- ldapPagingSize                : 500
- ldapPort                      : 389
- ldapQuotaAttribute            : quota
- ldapQuotaDefault              : 500 MB
- ldapTLS                       : 0
- ldapUserDisplayName           : displayName
- ldapUserDisplayName2
- ldapUserFilter                : (|(objectclass=inetOrgPerson))
- ldapUserFilterGroups
- ldapUserFilterMode            : 0
- ldapUserFilterObjectclass     : inetOrgPerson
- ldapUuidGroupAttribute        : auto
- ldapUuidUserAttribute         : auto
- turnOffCertCheck              : 0
- turnOnPasswordChange          : 0
- useMemberOfToDetectMembership : 1
```
</details>

<details>
        <summary>LDAP config s01 : AD</summary>

```
- hasMemberOfFilterSupport      : 1
- hasPagedResultSupport
- homeFolderNamingRule
- lastJpegPhotoLookup           : 0
- ldapAgentName                 : ***
- ldapAgentPassword             : ***
- ldapAttributesForGroupSearch
- ldapAttributesForUserSearch   : displayName;mail;cn
- ldapBackupHost
- ldapBackupPort
- ldapBase                      : OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapBaseGroups                : OU=Groups,OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapBaseUsers                 : OU=Users,OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapCacheTTL                  : 30
- ldapConfigurationActive       : 1
- ldapDefaultPPolicyDN
- ldapDynamicGroupMemberURL
- ldapEmailAttribute            : mail
- ldapExperiencedAdmin          : 0
- ldapExpertUUIDGroupAttr
- ldapExpertUUIDUserAttr        : sAMAccountname
- ldapExpertUsernameAttr        : sAMAccountname
- ldapGidNumber                 : gidNumber
- ldapGroupDisplayName          : cn
- ldapGroupFilter               : (&(|(objectclass=group)))
- ldapGroupFilterGroups
- ldapGroupFilterMode           : 0
- ldapGroupFilterObjectclass    : group
- ldapGroupMemberAssocAttr      : member
- ldapHost                      : ***
- ldapIgnoreNamingRules
- ldapLoginFilter               : (&(|(objectclass=person))(samaccountname=%uid))
- ldapLoginFilterAttributes
- ldapLoginFilterEmail          : 0
- ldapLoginFilterMode           : 0
- ldapLoginFilterUsername       : 1
- ldapNestedGroups              : 0
- ldapOverrideMainServer
- ldapPagingSize                : 500
- ldapPort                      : 389
- ldapQuotaAttribute
- ldapQuotaDefault              : 500 MB
- ldapTLS                       : 0
- ldapUserDisplayName           : displayName
- ldapUserDisplayName2
- ldapUserFilter                : (&(|(objectclass=person)))
- ldapUserFilterGroups
- ldapUserFilterMode            : 0
- ldapUserFilterObjectclass     : person
- ldapUuidGroupAttribute        : auto
- ldapUuidUserAttribute         : auto
- turnOffCertCheck              : 0
- turnOnPasswordChange          : 0
- useMemberOfToDetectMembership : 1
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** Linux (Kubuntu 17.04, Debian), Windows 10

### Logs

<details>
        <summary>Web server error log</summary>

```
nothing in particular
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"WkTYulVUXsIqix-vQo6xTAAAABE","level":4,"time":"2017-12-28T12:42:50+01:00","remoteAddr":"85.171.55.168","user":"philippe","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Test","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"No read permissions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/TagsPlugin.php(222): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\TagsPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1059): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(981): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Migration Libre...', Array, 1)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":254}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY5FVUXsIqix-vQo6xUgAAABA","level":1,"time":"2017-12-28T12:43:32+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"admin_audit","method":"GET","url":"\/core\/preview.png?file=%2Ftestfolder%2Fappstore+nextcloud.png&c=c8265e49dcda8bf629197664ce5170f0&x=32&y=32&forceIcon=0","message":"Preview accessed: \"ore nextcloud.png\" (width: \"32\", height: \"32\" crop: \"1\", mode: \"fill\")","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY5FVUXsIqix-vQo6xUwAAAAY","level":1,"time":"2017-12-28T12:43:32+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"admin_audit","method":"GET","url":"\/core\/preview.png?file=%2Ftestfolder%2Fcomments.png&c=ed89015deb41b0279a5a58b03cd9720e&x=32&y=32&forceIcon=0","message":"Preview accessed: \"nts.png\" (width: \"32\", height: \"32\" crop: \"1\", mode: \"fill\")","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY5GNEfn2FAD17z1Pe9gAAAFc","level":1,"time":"2017-12-28T12:43:33+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"admin_audit","method":"GET","url":"\/core\/preview.png?file=%2Ftestfolder%2Ftest.txt&c=0a42cf7b3a5f2deabc66182da9e5075f&x=32&y=32&forceIcon=0","message":"Preview accessed: \"txt\" (width: \"32\", height: \"32\" crop: \"1\", mode: \"fill\")","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY5mNEfn2FAD17z1Pe9wAAAFc","level":4,"time":"2017-12-28T12:43:34+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/testfolder\/test_paye","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"No read permissions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/TagsPlugin.php(222): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\TagsPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1059): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(981): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('testfolder\\\/tes...', Array, 1)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":254}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY6mNEfn2FAD17z1Pe-AAAAFc","level":4,"time":"2017-12-28T12:43:38+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Test\/test%20sub","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"No read permissions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/TagsPlugin.php(222): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\TagsPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1059): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(981): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Migration Libre...', Array, 1)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":254}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY9VVUXsIqix-vQo6xYAAAAAY","level":1,"time":"2017-12-28T12:43:49+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"admin_audit","method":"GET","url":"\/apps\/files_texteditor\/ajax\/loadfile?filename=test.txt&dir=%2Ftestfolder","message":"File accessed: \"\/testfolder\/test.txt\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"WkTY9lVUXsIqix-vQo6xYQAAAAY","level":1,"time":"2017-12-28T12:43:50+01:00","remoteAddr":"85.171.55.168","user":"pbernard","app":"admin_audit","method":"GET","url":"\/core\/preview.png?file=%2Ftestfolder%2Ftest.txt&c=1504589185&x=32&y=32&forceIcon=0","message":"Preview accessed: \"txt\" (width: \"32\", height: \"32\" crop: \"1\", mode: \"fill\")","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

```
</details>

<details>
        <summary>Browser log</summary>

```
nothing in particular
```
</details>

**Comment by labizette** [comment]
Hi, 
I have the same problem, did you find a solution to this ?

**Comment by fifh** [comment]
Unfortunately no !

**Comment by nickvergessen** [comment]
Well request URL does not work for shares, or at least it breaks often, that is exactly why the Tag rule was added and that is working fine.
Also note, that file listing is explicitly excluded and does continue to work, but pbernard should not be able to view/download/upload/modify any file:
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/access_control.html

**Comment by fifh** [comment]
Thank you @nickvergessen for your answer.
Ok let's forget Request URL.
But Tag rules are not working fine.
I have just changed the initial comment to be more precise and more right !

With a tag rule to prevent people from opening (listing) a tagged folder, the user admin (owner of the folder 'testfolder') can not even list the files in this folder.
But pbernard, who received the shared folder 'testfolder', can list the content of the folder (open the folder) and even see the content of the office files (ods, odt, doc, xls...) with collabora Online (the files are readonly).
In contrast, pbernard can't open / view a .txt file in this shared folder 'testfolder'. 

I think it's still a bug because of the different behaviors for the owner of the folder and the people receiving the shared folder, and mainly because with Collabora Online you can view the files in the restricted folder.

I think this issue has to be reopened.

**Comment by fifh** [comment]
Hello @nickvergessen 

As you said, "pbernard should not be able to view/download/upload/modify any file:
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/access_control.html"

The fact is that pbernard can view the content of files in a folder with a restricted access (with a tag rule).

It's clearly a bug : it's simply inconsistent with the documentation.

That's why I don't understand why this issue has been closed.

**Comment by nickvergessen** [comment]
Please report that to the Collabora developers
